---
version: "3.8"
services:
  taterland-discord-bot:
    image: p0t4t0sandwich/taterland-discord-bot:latest
    container_name: taterland-discord-bot
    environment:
      - TZ=UTC
      - DISCORD_TOKEN=           # Discord bot token
      - DISCORD_CLIENT_ID=       # Used to update slash commands
      - DISCORD_ADMIN_IDS=       # Comma separated list of admin ids
      - AMP_URL=                 # URL of the AMP server
      - AMP_USERNAME=            # Username for the AMP server
      - AMP_PASSWORD=            # Password for the AMP server
      - REST_PORT=               # Port to listen on
      - MONGODB_URI=             # MongoDB connection string
      - MONGODB_DB=              # MongoDB database name
      - DOMAIN=                  # Domain name for the REST API
      - ROOT_ENDPOINT=           # Root endpoint for the REST API
      - AUTH_TOKEN=              # Auth token for the REST API
    ports:
      - "0.0.0.0:3002:3002"
    restart: unless-stopped
