---
version: "3.8"
services:
  taterland-discord-bot:
    image: p0t4t0sandwich/taterland-discord-bot:latest
    container_name: taterland-discord-bot
    environment:
      - TZ=UTC
      - DISCORD_TOKEN=           # Discord bot token
      - DISCORD_CLIENT_ID=       # Used to update slash commands
      - DISCORD_ADMIN_IDS=       # Comma separated list of admin ids
      - AMP_API_URL=                 # URL of the AMP server
      - AMP_API_USERNAME=            # Username for the AMP server
      - AMP_API_PASSWORD=            # Password for the AMP server
    restart: unless-stopped
