name: DockerHub CI

on:
  push:
    branches: [ main ]

jobs:
  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #     - run: npm i
  #     - run: npm test
  #     - run: npm run build

  build:
    name: Build
    # needs: test
    runs-on: ubuntu-latest
    environment: taterland-discord-bot
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Check out code
        uses: actions/checkout@v3
      -
        name: Set up Bun
        uses: oven-sh/setup-bun@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Run Bun Build
        run: bun i && bun run build
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/taterland-discord-bot:latest
